---
title: "relational graphs hw"
output: html_document
---


```{r social graphing packages}
library(sna)    # network function
library(GGally) # ggnet2 function

```


https://www.rdocumentation.org/packages/GGally/versions/1.3.2/topics/ggnet2

We will use the cities network data as provided via https://networkdata.ics.uci.edu/netdata/html/cities.html. Read the cities network into R via the provided Rdata file. Then recreate the graph provided in the PPT. Set a seed to 1 before creating the graph to recreate the graph exactly.
```{r problem 1}


load("cities.RData") # RData created from another R session in which the save("ceos") command was used to capture session information. load(data file) recreates session including the use of variable names. In this case, the CEOs network is read into memory.
class(cities)
cities

set.seed(1)
# Viewing the graph before calculating metrics
ggnet2(net = cities, 
       #mode = "kamadakawai",
       size.min = 36,
       label = TRUE, 
       edge.color = "red",
       label.size = 3, 
       size = "degree") # size varies by number of links


cc<-clique.census(cities, clique.comembership = "bysize") # cliques are "subgroups" within the network
cc$clique.count # CEO 14 belongs to 7 cliques, Club 3 is connected to 22 cliques



```
